// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3It6781XkKv5jsL-LdJuo6NHaRAo1HVQ',
    appId: '1:411362004019:web:186215ef3132c8503fe746',
    messagingSenderId: '411362004019',
    projectId: 'flutterbloclogin-c9929',
    authDomain: 'flutterbloclogin-c9929.firebaseapp.com',
    storageBucket: 'flutterbloclogin-c9929.appspot.com',
    measurementId: 'G-YERF0XZZT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-TMSvWY-PEzIvI98vuQuPk3ksIDufnFI',
    appId: '1:411362004019:android:22b384887134001a3fe746',
    messagingSenderId: '411362004019',
    projectId: 'flutterbloclogin-c9929',
    storageBucket: 'flutterbloclogin-c9929.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvF1R6BMB9mCCpM3ahvxkQll37FlbwpA4',
    appId: '1:411362004019:ios:6e247898ad4af8be3fe746',
    messagingSenderId: '411362004019',
    projectId: 'flutterbloclogin-c9929',
    storageBucket: 'flutterbloclogin-c9929.appspot.com',
    iosBundleId: 'com.example.flutterBlocFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvF1R6BMB9mCCpM3ahvxkQll37FlbwpA4',
    appId: '1:411362004019:ios:6e247898ad4af8be3fe746',
    messagingSenderId: '411362004019',
    projectId: 'flutterbloclogin-c9929',
    storageBucket: 'flutterbloclogin-c9929.appspot.com',
    iosBundleId: 'com.example.flutterBlocFirebaseLogin',
  );
}
